### ISSUE TITLE
Getting "Unable to resize process, elevated privileges may be required" on several apps

### ISSUE THREAD

**Issue by thesoloist-1** [caoyue/WindowResizer#63]
Any ideas how to fix this? Tried running as administrator but still doesn't work.

**Comment by Gonnno** [comment]
I am in the same situation with a software, if you see any solution... 
I will do the same.

**Comment by thesoloist-1** [comment]
> I am in the same situation with a software, if you see any solution... 
> 
> I will do the same.

Turning off Admin Approval Mode using Secpol worked for me.

**Comment by caoyue** [comment]
Hi, can you provide some of the apps that are causing the problem?

**Comment by Gonnno** [comment]
Hello, only the "Macro Recorder by Jitbit" software has this issue.

**Comment by thesoloist-1** [comment]
I have a couple of custom apps that are affected by this, but turning off admin approval worked for them.

**Comment by nisocapitalfx** [comment]
How can I run windows resizer on one computer with two users at the same time please, I can't, it only lets me open it with one user

**Comment by avengerx** [comment]
An example of this is Process Explorer (procexp64.exe). Sometimes WindowResizer doesn't even save the process in the list of saved positions.

Tested with v1.3.4+da97300, running as normal user -- running as admin bricked WindowResizer bundled executable (WindowResizer-1.3.4.exe), more info at the end

1. Run Process Explorer as a limited user (launch it without doing anything fancy)
2. Save All + Restore all (works fine)
3. Elevate procexp (File > Show details for all Processes)
4. Save all. It lists process explorer in the list of saved windows
5. Restore all. Resized/moved Process Explorer won't be fixed.

I couldn't reproduce again the issue where procexp64.exe doesn't get listed. It was consistently happening, then I restarted procexp to check in non-elevated mode and it listed.

Well then I tried to restart explorer.exe so that Procexp became "orphan" to see if WindowResizer wouldn't find procexp anymore, lost access to WindowResizer tray icon and couldn't open settings window. Killing WindowResizer process broken the tool such as I can't start it anymore. It starts, mysteriously tries to start itself again and fails with "installation failed, re run as normal user instead of admin". But now that's another problem. :P (**edit:** issue with .NET "bundled" executable, using the portable version avoided the issue, but there's still some cached .NET leftover that's breaking the bundled version. it was triggered by killing the self-extracted executable and the issue may be related with trying to run the bundled exe once, as admin)

**edit2:** running *the portable version* as administrator avoids the issue.
